apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yaxt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cbig-tenant/rhtap-demo-app/hacbs-test-project-yaxt@sha256:3db34e11a17a5a6430a891cec1d747da530ea15f3c76cf5ea9fcf799b663fc86
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
