apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yaxt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cbig-tenant/rhtap-demo-app/hacbs-test-project-yaxt@sha256:be71dbc7200c864edd5abc92d38e5613d12d61b432655a75e90c99b48332cbb3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
