apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yaxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yaxt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yaxt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yaxt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yaxt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cbig-tenant/rhtap-demo-app/hacbs-test-project-yaxt@sha256:57b564e8ab9d375cc0a85ef7f1e076d5126612d590ac2e2f03e4693869b92b71
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
